### ISSUE TITLE
load_texture() segfaults in multi-threaded environment

### ISSUE THREAD

**Issue by sloganking** [not-fl3/macroquad#424]
# Problem

``cargo.toml`` dependencies:

```toml
[dependencies]
macroquad = "0.3"
futures = {version = "0.3.21", features = ["thread-pool", "executor"]}
```
``main.rs``:
```rust
use futures::task::SpawnExt;
use futures::executor::ThreadPool;
use macroquad::prelude::load_texture;

async fn test_load_texture(dir: &str){
    println!("test1");
    load_texture(&dir).await;
    println!("test2");
}

#[macroquad::main("test")]
async fn main() {
    let pool = ThreadPool::new().unwrap();

    let f = test_load_texture("./test.png");
    
    pool.spawn(f).unwrap();

    println!("Hello there!");
}
```

When ``./text.png`` exists, running the above yields

```
Hello there!
test1
Segmentation fault (core dumped)
```

# Note

- This also seems to happen with ``Texture2D::from_rgba8()``

- Could this be related to the behavior discussed in #421?
